### ISSUE TITLE
Do I need to address "INTERNAL ERROR: not all protocols have been initialized"?

### ISSUE THREAD

**Issue by lofidevops** [emanuele-f/DNSleak#2]
After running `sudo dnsleak wlp1s0` I get:

````
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
No leak detected
````

or (with VPN disabled)

````
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
=== Leaks detected ===
````

...what does this error message mean? Is there anything I have to do (install, recompile...)?

**Comment by emanuele-f** [comment]
I was fairly too optimistic about api changes when I built this project. I'm upgrading the build instructions to pull the old version of nDPI and use it.

**Comment by emanuele-f** [comment]
Ok, nDPI dependency fixed with 8eab59037e6daa0c354db7bddf05313271409c5a .
Please retry with new version and let me know.

**Comment by lofidevops** [comment]
It works, thanks!

**Comment by emanuele-f** [comment]
Great! Thank you :)
