### ISSUE TITLE
Package for Debian

### ISSUE THREAD

**Issue by lofidevops** [emanuele-f/DNSleak#3]
**User story:** I am a Debian user. I want to install dnsleak via apt, so that updates are in synch with my system packages.

**Suggested solution:** [RFP #879005](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=879005)

**Comment by emanuele-f** [comment]
Dependencies are minimal, what about using `checkinstall` to easily install and remove? I don't expect to update this further, so an official package maybe is inappropriate.

**Comment by alexmyczko** [comment]
http://sid.ethz.ch/debian/dnsleak/

there you go.

**Comment by emanuele-f** [comment]
Hi @alexmyczko, thank you very much! Can you provide a simple script to build the package? I can integrate it into the Makefile so that others can build the package easily. Maybe you can do a pull request?

**Comment by alexmyczko** [comment]
dget -x http://sid.ethz.ch/debian/dnsleak/dnsleak_0%2Bgit20171101-1.dsc
cd dnsleak*/
debuild
cd ..
dpkg -i *.deb

**Comment by emanuele-f** [comment]
Hi, thank you for sharing. Unfortunately, I cannot make it work. It complains about missing changelog. Can you fix this? Moreover, is there a way to just build the packet from local source directory? I mean, I wish to add a target on the Makefile of this project (pointing to your repository for the deb stuff), but I would avoid downloading the source again.

![screenshot at 2017-11-09 17-01-44](https://user-images.githubusercontent.com/5488003/32615284-b0e7614c-c56f-11e7-9edf-fcf00d9002d3.png)

**Comment by alexmyczko** [comment]
Because you probably missed the 2nd command? You should be in a directory called dnsleak-0+git20171101. Your screenshot doesn't show your input. For bug reports, it is very clever to include not just the result, but also the action taken before the result.

**Comment by emanuele-f** [comment]
Hi, sorry for the screenshot above, I took it quickly from my virtualbox. The problem was indeed the missing `cd`. I managed to build and install it now. I've integrated the man page and added reference to the deb into the README. Thank you.
